//package com.jdt_160422042.trivia_master
//
//import android.content.Context
//import android.content.SharedPreferences
//
//object Global {
//    val questions: Array<Question> = arrayOf(
//        // Easy - Geography
//        Question("What is the capital of Indonesia?","Banten",
//            "Jakarta","Surabaya","Bandung","Jakarta",
//            Difficulty.Easy, Type.Geography),
//        Question("What is the capital of France?","London",
//            "Rome","Paris","Berlin","Paris",
//            Difficulty.Easy, Type.Geography),
//        Question("What is the currency used in Japan?","Yuan",
//            "Yen","Won","Rupiah","Yen",
//            Difficulty.Easy, Type.Geography),
//        Question("What is the largest ocean on Earth?", "Arctic Ocean",
//            "Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Pacific Ocean",
//            Difficulty.Easy, Type.Geography),
//        Question("Which continent is home to the Great Wall of China?", "Europe",
//            "Africa", "Asia", "South America", "Asia",
//            Difficulty.Easy, Type.Geography),
//
//        // Easy - History
//        Question("Who was the fifth president of Indonesia?","Susilo Bambang Yudhoyono",
//            " Joko Widodo","Megawati Sukarnoputri","Abdurrahman Wahid",
//            "Megawati Sukarnoputri",Difficulty.Easy, Type.History),
//        Question("Who was the first president of Indonesia?","Sukarno",
//            "Suharto","B. J. Habibie","Abdurrahman Wahid","Sukarno",
//            Difficulty.Easy, Type.History),
//        Question("When did Indonesia declared independence?","1932",
//            "1944","1945","1954","1945",
//            Difficulty.Easy, Type.History),
//        Question("Which nation invaded Indonesia?","Malaya",
//            "Tursk","Dutch","Thailand","Dutch",
//            Difficulty.Easy, Type.History),
//        Question("When is the Indonesian Independence Day","20th May",
//            "17th August","1st July","30th October","17th August",
//            Difficulty.Easy, Type.History),
//
//        // Easy - Math
//        Question("What is the sum of 15 and 7?", "9", "10",
//            "15", "18", "18", Difficulty.Easy, Type.Math),
//        Question("What is the sum of 5 and 17?", "16", "22",
//            "24", "35", "24", Difficulty.Easy, Type.Math),
//        Question("What is the multiplication of -1 and 8?", "7", "8",
//            "-8", "-18", "-8", Difficulty.Easy, Type.Math),
//        Question("What is the multiplication of 12 and 3?", "12","15", "24",
//            "36", "36", Difficulty.Easy, Type.Math),
//        Question("What is value of pi?", "3.14", "22/7",
//            "3.14159", "π", "π", Difficulty.Easy, Type.Math),
//
//        // Medium - Geography
//        Question("What is the official language of Brazil?","Spanish",
//            "Portuguese","French","English","Portuguese",
//            Difficulty.Medium, Type.Geography),
//        Question("What is the capital of Australia?","Sydney",
//            "Melbourne","Canberra","Perth","Canberra",
//            Difficulty.Medium, Type.Geography),
//        Question("What is the name of the largest desert in the world (by area)?","Sahara Desert",
//            "Gobi Desert","Arabian Desert","Australian Desert","Sahara Desert",
//            Difficulty.Medium, Type.Geography),
//        Question("What is the neigboring country of Indonesia?","Thailand",
//            "Bali","Singapore","New Zealand","Singapore",
//            Difficulty.Medium, Type.Geography),
//        Question("What is the currency of Vietnam?","Dong",
//            "Rupee","Kip","Kyat","Dong",
//            Difficulty.Medium, Type.Geography),
//
//        // Medium - History
//        Question("During which war was the atomic bomb first used?", "World War I",
//            "World War II", "Korean War", "Vietnam War", "World War II",
//            Difficulty.Medium, Type.History),
//        Question("Who is considered the father of modern physics?", "Isaac Newton",
//            "Albert Einstein", "Galileo Galilei", "Stephen Hawking", "Isaac Newton",
//            Difficulty.Medium, Type.History),
//        Question("The Berlin Wall, a symbol of the Cold War, divided which two cities?", "Moscow and Leningrad",
//            "London and Paris", "East Berlin & West Berlin", "North Korean & South Korea",
//            "East Berlin & West Berlin",Difficulty.Medium, Type.History),
//        Question("Who was the leader of the Soviet Union during World War II?", "Vladimir Putin",
//            "Nikita Khrushchev", "Joseph Stalin", "Mikhail Gorbachev", "Joseph Stalin",
//            Difficulty.Medium, Type.History),
//        Question("What is the name of the first artificial Earth satellite launched by the Soviet Union?","Sputnik 1",
//            "Explorer 1","Luna 1","Apollo 1","Sputnik 1",
//            Difficulty.Medium, Type.History),
//
//        // Medium - Math
//        Question("A train travels 200 km in 4 hours. What is the average speed of the train in km/h?",
//            "40 km/h", "50 km/h","55 km/h", "60 km/h", "50 km/h",
//            Difficulty.Medium, Type.Math),
//        Question("A simple equation is given: 3x + 5 = 13. What is the value of x?",
//            "1", "2","4", "6", "6", Difficulty.Medium, Type.Math),
//        Question("What is the value of 6!?", "6", "36",
//            "360", "720", "720", Difficulty.Medium, Type.Math),
//        Question("What is the value of - | 18 - 20 |?", "-2","2", "4",
//            "-4", "-2", Difficulty.Medium, Type.Math),
//        Question("What is NOT a prime number?", "2", "3",
//            "4", "5", "5", Difficulty.Medium, Type.Math),
//
//        // Hard - Geography
//        Question("Which of the following countries borders both the Atlantic Ocean and the Pacific Ocean?",
//            "Brazil","Canada","China","Australia","Canada",
//            Difficulty.Hard, Type.Geography),
//        Question("The Great Barrier Reef, the world's largest coral reef system, is located off the coast of which country?",
//            "Australia","Indonesia","Japan","India","Australia",
//            Difficulty.Hard, Type.Geography),
//        Question("Mount Kilimanjaro is the highest mountain in Africa. Which country is home to Mount Kilimanjaro?",
//            "Egypt","Tanzania","Morocco","Uganda","Tanzania",
//            Difficulty.Hard, Type.Geography),
//        Question("The capital of France is Paris. On which major river is Paris located?",
//            "Rhine River","Thames River","Seine River","Danube River",
//            "Seine River",Difficulty.Hard, Type.Geography),
//        Question("What is the currency of Hungary?","Forint",
//            "Shilling","Krone","Euro","Forint",
//            Difficulty.Hard, Type.Geography),
//
//        // Hard - History
//        Question("Invented in 1957, what was the first high-level programming language?","C++",
//            "Java","COBOL","FORTRAN","FORTRAN",
//            Difficulty.Hard, Type.History),
//        Question("What is the name of the woman who is considered the \"first computer programmer\" for her work on the Charles Babbage's Analytical Engine?",
//            "Grace Hopper","Margaret Hamilton","Ada Lovelace","Radia Perlman",
//            "Ada Lovelace",Difficulty.Hard, Type.History),
//        Question("C is a general-purpose programming language developed by whom?","Bjarne Stroustrup",
//            "Guido van Rossum","Dennis Ritchie","James Gosling","Dennis Ritchie",
//            Difficulty.Hard, Type.History),
//        Question("What was the first object-oriented programming language?","COBOL",
//            "Simula 67","Visual Basic","Pascal","Simula 67",
//            Difficulty.Hard, Type.History),
//        Question("What programming language was developed by Google and is known for its speed and efficiency?",
//            "Go","Delphi","Swift","Kotlin","Go",
//            Difficulty.Hard, Type.History),
//
//        // Hard - Math
//        Question("Solve the system of equations: 2x + y = 5, x - 3y = -1", "x = 1, y = 3", "x = 2, y = 1",
//            "x = -1, y = 2", "x = 3, y = -1", "x = -1, y = 2", Difficulty.Hard, Type.Math),
//        Question("Find the sine (sin) of a 30-degree angle", "0.5", "0.707",
//            "1", "1.5", "0.707", Difficulty.Hard, Type.Math),
//        Question("A circle has a circumference of 12π cm. What is the radius of the circle?",
//            "2cm", "3cm","6cm", "12cm", "6cm", Difficulty.Hard, Type.Math),
//        Question("A sequence is given: 2, 5, 8, 11, ... What is the 6th term in the sequence?",
//            "15","16", "17","18", "18", Difficulty.Hard, Type.Math),
//        Question("What is the derivative of the function f(x) = x^2?", "2x", "x",
//            "1", "2", "2x", Difficulty.Hard, Type.Math),
//    )
//
//    val types: Array<String> = arrayOf(Type.History.name, Type.Geography.name, Type.Math.name)
//}